#ifndef ASSEMBLER_H

#define ASSEMBLER_H

#define LINE_LENGTH 80 /* maximum chars per line */
#define LABEL_LENGTH 31 /* maximum chars of the label */
#define REGISTER_LENGTH 3 /* a register's name contains 3 chars */

/* When we need to specify if label should contain a colon or not */
enum COLON_F_or_T {NO_COLON, COLON};



typedef enum  {
     OK,NOT_OK,LABEL_DATA_ALREADY_EXISTS,LABEL_ALREADY_EXISTS,LABEL_TOO_LONG, LABEL_INVALID_FIRST_CHAR,LABEL_CONSISTS_ONLY_DIGITS ,LABEL_ONLY_ALPHANUMERIC,
    LABEL_CANT_BE_COMMAND,LABEL_ONLY, LABEL_CANT_BE_REGISTER,COLON_NOT_IN_RIGHT_PLACE,
    DIRECTIVE_NO_PARAMS, DIRECTIVE_INVALID_NUM_PARAMS, DATA_COMMAS_IN_A_ROW, DATA_EXPECTED_NUM,
    DATA_EXPECTED_COMMA_AFTER_NUM, DATA_UNEXPECTED_COMMA,
    STRING_TOO_MANY_OPERANDS, STRING_OPERAND_NOT_VALID, STRUCT_EXPECTED_STRING,
    STRUCT_INVALID_STRING, EXPECTED_COMMA_BETWEEN_OPERANDS, STRUCT_INVALID_NUM, STRUCT_TOO_MANY_OPERANDS,
    EXTERN_NO_LABEL, EXTERN_INVALID_LABEL, EXTERN_TOO_MANY_OPERANDS,
    COMMAND_NOT_FOUND, COMMAND_UNEXPECTED_CHAR, COMMAND_TOO_MANY_OPERANDS,
    COMMAND_INVALID_METHOD, COMMAND_INVALID_NUMBER_OF_OPERANDS, COMMAND_INVALID_OPERANDS_METHODS,
    ENTRY_LABEL_DOES_NOT_EXIST, ENTRY_CANT_BE_EXTERN, COMMAND_LABEL_DOES_NOT_EXIST,
    CANNOT_OPEN_FILE,REGISTER_DOES_NOT_EXIST,TOO_MUCH_OPERANDS,TOO_MUCH_STRINGS,
    ENTRY_NOT_ENOUGH_LABELS,ENTRY_TOO_MUCH_LABELS,LABEL_DOES_NOT_EXIST_IN_SYMBOL_LIST,
    WRONG_ADDERSSING_MODE
} ErrorType;

/* A/R/E modes ordered by their numerical value */
enum ARE {ABSOLUTE, EXTERNAL, RELOCATABLE};

#endif